[package]
name = "provider-archive"
version = "0.7.0"
authors = ["wasmCloud Team"]
edition = "2021"
description = "Library for reading and writing wasmCloud capability provider archive files"
license = "Apache-2.0"
homepage = "https://github.com/wasmcloud/provider-archive"
documentation = "https://docs.rs/provider-archive"
readme = "README.md"
keywords = ["jwt", "zip", "archive", "security", "wasmcloud"]
categories = ["cryptography", "authentication", "wasm"]

[dependencies]
wascap = "0.8.0"
data-encoding = "2.3.1"
ring = "0.16"
tokio = { version = "1.17.0", features = ["io-util"], default-features = false }
async-compression = { version = "0.3", default-features = false, features = ["tokio", "gzip"] }
tokio-tar = "0.3"
tokio-stream = "0.1"

[dev-dependencies]
# Turn on the test feature for our tests
tokio = { version = "1.17.0", features = ["rt", "macros"] }
tempfile = "3.2"
